import {Dimensions, Platform} from 'react-native';
import {moderateScale} from 'react-native-size-matters';

export const screenWidth = Dimensions.get('window').width;
export const screenHeight = Dimensions.get('window').height;
// describing sizes for styling components and text
export const fontSizes = {
  xs: moderateScale(4),
  xss: moderateScale(6),
  sm: moderateScale(8),
  m: moderateScale(10),
  ssm: moderateScale(12),
  smm: moderateScale(14),
  md: moderateScale(16),
  mdd: moderateScale(18),
  lg: moderateScale(20),
  xl: moderateScale(24),
  xxl: moderateScale(26),
  xlll: moderateScale(32),
  xll: moderateScale(34),
};

export const paddingSizes = {
  xs: moderateScale(4),
  xss: moderateScale(6),
  sm: moderateScale(8),
  m: moderateScale(10),
  ssm: moderateScale(12),
  smm: moderateScale(14),
  md: moderateScale(16),
  mdd: moderateScale(18),
  lg: moderateScale(20),
  xl: moderateScale(24),
  xxl: moderateScale(26),
  xlll: moderateScale(32),
  xll: moderateScale(34),
};

export const marginSizes = {
  xs: moderateScale(4),
  xss: moderateScale(6),
  sm: moderateScale(8),
  m: moderateScale(10),
  ssm: moderateScale(12),
  smm: moderateScale(14),
  md: moderateScale(16),
  mdd: moderateScale(18),
  lg: moderateScale(20),
  xl: moderateScale(24),
  xxl: moderateScale(26),
  xlll: moderateScale(32),
  xll: moderateScale(34),
};

export const sizes = {
  micro: moderateScale(1),
  xxs: moderateScale(2),
  xs: moderateScale(4),
  xss: moderateScale(6),
  sm: moderateScale(8),
  m: moderateScale(10),
  ssm: moderateScale(12),
  smm: moderateScale(14),
  md: moderateScale(16),
  mdd: moderateScale(18),
  lg: moderateScale(20),
  xl: moderateScale(24),
  xxl: moderateScale(26),
  xlll: moderateScale(32),
  xll: moderateScale(34),
  homeCardHeight: '100%',
  homeCardWidth: '100%',
  skelSmallBoxheight: moderateScale(70),
  skelSmallBoxWidth: moderateScale(75),
  bigSkellHeight: screenHeight * 0.4,
  restaurantImageSliderHeight: screenHeight * 0.3,
  swipeIconSize: moderateScale(70),
  commentInputHeight: moderateScale(100),
  WINDOW_WIDTH: screenWidth,
  WINDOW_HEIGHT: screenHeight,
  googlePlaceDefaultInputHeight: moderateScale(44),
  socialButtonRadius: moderateScale(100),
  defaultButtonRadius: moderateScale(100),
  editCameraIcon: moderateScale(44),
  reviewInputHeight: moderateScale(168),
  reviewInputMinHeight: moderateScale(80),
  reviewImageWidth: moderateScale(96),
  reviewImageHeight: moderateScale(96),
  bottomNavBarSize: moderateScale(96),
  toastView: moderateScale(80),
  tooltipCircle: moderateScale(45),
  tagButtonHeight: moderateScale(60),
  homeCoverHeight: '50%',
  verifySmallIconHeight: moderateScale(48),
  textInputHeight: moderateScale(48),
  verifyIcon: moderateScale(14),
  threeDot: moderateScale(24),
  polygon: moderateScale(16),
  verifySocialIcon:
    Platform.OS === 'ios' ? moderateScale(16) : moderateScale(14),
  orderItemImageSize: moderateScale(48),
  defaultButtonHeight: moderateScale(48),
  largeButtonHeight: moderateScale(56),
  smallButtonHeight: moderateScale(40),
  sectionHeaderHeight: moderateScale(50),
  sectionItemHeight: moderateScale(120),
  dropdownRowHeight: moderateScale(46),
  small32ButtonHeight: moderateScale(32),
  shareButtonWidth: moderateScale(126),
};

// default parameters used in app
export const appParams = {
  padding: paddingSizes.md,
  margin: marginSizes.lg,
  titleFont: fontSizes.lg,
  overlayPadding: paddingSizes.sm,
};

export const iconSizes = {
  default: moderateScale(30),
  buttonIcon: moderateScale(17),
  tiny: moderateScale(20),
  bottomBarIcon: moderateScale(24),
  small: moderateScale(25),
  closeIcon: moderateScale(18),
  homeScreenLogoHeight: moderateScale(34),
  homeScreenLogoWidth: moderateScale(147),
  reviewIcon: moderateScale(36),
  addImageIcon: moderateScale(24),
  largeIcon: moderateScale(90),
  iceCreamIconWidth: moderateScale(172),
  iceCreamIconHeight: moderateScale(124),
  socialScreenBlankListIcon: moderateScale(128),
  swipeElementIcon: moderateScale(45),
  videoLoaderHeight: moderateScale(4),
  videoLoaderRadius: moderateScale(50),
  ratingIconSmall: moderateScale(16),
  diceIcon: moderateScale(24),
  surveyIcon: moderateScale(40),
  homePageNoPhotoIconHeight: moderateScale(50),
  homePageNoPhotoIconWidth: moderateScale(80),
  locationPinIconSize: moderateScale(13),
  connectIcon: moderateScale(18),
  starIcon: moderateScale(50),
  heartIcon: moderateScale(26),
  shareIconWidth: moderateScale(19),
  shareIconHeight: moderateScale(24),
  heartFilledIcon: moderateScale(24.5),
  trashIcon: moderateScale(26),
  orderIcon: moderateScale(18),
  dotIcon: moderateScale(4),
  createListClose: moderateScale(24),
  threeDot: moderateScale(14),
  hoverIcon: moderateScale(22),
  grublrLogoHome: moderateScale(40),
  diningTable: moderateScale(85),
  plusIcon: moderateScale(34),
  globalIcon: moderateScale(16),
  editIcon: moderateScale(24),
  mapFilterIcon: moderateScale(18),
  currentLocationIcon: moderateScale(64),
  restaurantPin: moderateScale(50),
  myLocation: moderateScale(30),
};
